name: pokedex_ai
description: A Flutter application for browsing Pokemon with AI-generated descriptions.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Dependencies
  cupertino_icons: ^1.0.2
  
  # HTTP & API
  http: ^1.1.0
  google_generative_ai: ^0.4.3
  
  # State Management (optional, uncomment if needed)
  # provider: ^6.1.1
  # riverpod: ^2.4.9
  
  # Local Storage (optional, uncomment if needed)
  # shared_preferences: ^2.2.2
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  
  # Utilities
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Uncomment and add assets if needed
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Uncomment and add custom fonts if needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700